In [13]:
import numpy as np

In [14]:
# Chessboard size
board_size = 8

# Knight moves
knight_moves = [(2, 1), (2, -1), (-2, 1), (-2, -1), (1, 2), (1, -2), (-1, 2), (-1, -2)]

# Matrix C: Calculate the number of possible moves for each square
C = np.zeros((board_size, board_size), dtype=int)
for i in range(board_size):
    for j in range(board_size):
        count = 0
        for move in knight_moves:
            ni, nj = i + move[0], j + move[1]
            if 0 <= ni < board_size and 0 <= nj < board_size:
                count += 1
        C[i, j] = count

# Adjacency Matrix A
A = np.zeros((board_size * board_size, board_size * board_size), dtype=int)
for i in range(board_size):
    for j in range(board_size):
        pos = i * board_size + j
        for move in knight_moves:
            ni, nj = i + move[0], j + move[1]
            if 0 <= ni < board_size and 0 <= nj < board_size:
                neighbor_pos = ni * board_size + nj
                A[pos, neighbor_pos] = 1

# Degree Matrix D and Degree Vector d
D = np.diag(A.sum(axis=1))
d = np.diag(D)

# Transition Matrix P (uniform probabilities)
P = np.zeros_like(A, dtype=float)
for i in range(board_size * board_size):
    if d[i] > 0:
        P[i] = A[i] / d[i]

# Simulate knight's movements and compute matrix S
num_simulations = 100000
visits = np.zeros((board_size, board_size), dtype=int)

# Starting from a random initial position
current_position = (np.random.randint(0, board_size), np.random.randint(0, board_size))

for _ in range(num_simulations):
    i, j = current_position
    visits[i, j] += 1
    possible_moves = [(i + move[0], j + move[1]) for move in knight_moves if 0 <= i + move[0] < board_size and 0 <= j + move[1] < board_size]
    current_position = possible_moves[np.random.randint(len(possible_moves))]

# Normalize to get empirical distribution S
S = visits / visits.sum()

# Matrix R: Store average return times
R = np.zeros((board_size, board_size))
for i in range(board_size):
    for j in range(board_size):
        if S[i, j] > 0:
            R[i, j] = 1 / S[i, j]  # Reciprocal of stationary distribution

# Print results as specified
print("Adjacency Matrix A:")
print(A)

print("\nDegree Matrix D:")
print(D)

print("\nDegree Vector d:")
print(d)

print("\nTransition Matrix P:")
print(P)

print("\nMatrix C (Number of possible moves):")
print(C)

print("\nMatrix S (Empirical Distribution of visits):")
print(S)

print("\nMatrix R (Average return times):")
print(R)

Adjacency Matrix A:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Degree Matrix D:
[[2 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 4 ... 0 0 0]
 ...
 [0 0 0 ... 4 0 0]
 [0 0 0 ... 0 3 0]
 [0 0 0 ... 0 0 2]]

Degree Vector d:
[2 3 4 4 4 4 3 2 3 4 6 6 6 6 4 3 4 6 8 8 8 8 6 4 4 6 8 8 8 8 6 4 4 6 8 8 8
 8 6 4 4 6 8 8 8 8 6 4 3 4 6 6 6 6 4 3 2 3 4 4 4 4 3 2]

Transition Matrix P:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

Matrix C (Number of possible moves):
[[2 3 4 4 4 4 3 2]
 [3 4 6 6 6 6 4 3]
 [4 6 8 8 8 8 6 4]
 [4 6 8 8 8 8 6 4]
 [4 6 8 8 8 8 6 4]
 [4 6 8 8 8 8 6 4]
 [3 4 6 6 6 6 4 3]
 [2 3 4 4 4 4 3 2]]

Matrix S (Empirical Distribution of visits):
[[0.006   0.00859 0.01149 0.01186 0.012   0.0122  0.00912 0.00612]
 [0.00888 0.01162 0.01753 0.01774 0.01815 0.01824 0.01232 0.00911]
 [0.01129 0.01752 0.0243